import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: "1",

    itemName: "Roadster",
    image: "https://img.freepik.com/free-photo/portrait-handsome-smiling-stylish-young-man-model-wearing-jeans-clothes-sunglasses-fashion-man_158538-5023.jpg?size=626&ext=jpg&ga=GA1.1.1963083236.1682951392&semt=sph",
    description: "A stylish and durable jacket for men.",
    rating: 4.8,
    reviews: 12,
    size: "XL",
    category: "Men",
    oldPrice: 2099,
    newPrice: 1154,
    discount: 45,
    isTrending: true,
    inStock: true,
    delivery_time: "4-6 business days",
    fewLeft: true,
  },
  {
    _id: "2",
    itemName: "Mast & Harbour",
    image: "https://img.freepik.com/free-psd/simple-black-men-s-tee-mockup_53876-57893.jpg?size=626&ext=jpg",
    description: "A premium quality and stylish T-shirt for men.",
    rating: 4.5,
    reviews: 10,
    size: "L",
    category: "Men",
    oldPrice: 1499,
    newPrice: 704,
    discount: 53,
    isTrending: false,
    inStock: true,
    delivery_time: "2-4 business days",
    fewLeft: true,

  },
  {
    _id: "3",
    itemName: "Nautica",
    image: "https://img.freepik.com/free-photo/fashion-portrait-young-man-white-shirt-poses-wall-with-contrast-shadows_186202-4512.jpg?size=626&ext=jpg",
    description: "A classic and formal shirt for men.",
    rating: 3.9,
    reviews: 6,
    size: "XXL",
    category: "Men",
    oldPrice: 1599,
    newPrice: 959,
    discount: 40,
    isTrending: true,
    inStock: false,
    delivery_time: "2-4 business days",
    fewLeft: false,

  },
  {
    _id: "4",
    itemName: "CottonKing",
    image: "https://img.freepik.com/free-photo/attractive-man-wearing-dark-blue-suit_1139-1.jpg?size=626&ext=jpg&ga=GA1.2.1963083236.1682951392&semt=ais",
    rating: 4.2,
    reviews: 10,
    size: "S",
    category: "Men",
    oldPrice: 2999,
    newPrice: 1699,
    discount: 45,
    isTrending: true,
    description: "A sophisticated and stylish blazer for Men.",
    delivery_time: "2-4 business days",
    inStock: true,
    fewLeft: true,
  },
  {
    _id: "5",
    itemName: "Ahika",
    image: "https://img.freepik.com/premium-photo/pretty-girl-posing-confidently-with-attitude-fashion-shoot-wearing-desi-dress-street_658768-439.jpg?size=626&ext=jpg",
    description: "A comfortable and trendy Dress for women.",
    rating: 4.8,
    reviews: 15,
    size: "M",
    category: "Women",
    oldPrice: 1587,
    newPrice: 890,
    discount: 43,
    isTrending: false,
    inStock: true,
    delivery_time: "3-5 business days",
    fewLeft: false,
  },
  {
    _id: "6",

    itemName: "H&M",
    image: "https://img.freepik.com/premium-psd/kid-wearing-tshirt-mockup-design_23-2149404828.jpg?size=626&ext=jpg",
    description: "A comfortable and stylish T-shirt for kids.",
    rating: 3.9,
    reviews: 8,
    size: "S",
    category: "Kids",
    oldPrice: 900,
    newPrice: 499,
    discount: 44,
    isTrending: false,
    inStock: true,
    delivery_time: "2-4 business days",
    fewLeft: true,

  },
  {
    _id: "7",
    itemName: "Indo Era",
    image: "https://img.freepik.com/premium-psd/sweater-mockup-with-zig-zag-pattern-women-s-casual-apparel_53876-98829.jpg?size=626&ext=jpg",
    description: "A cozy and stylish sweater for women.",
    rating: 4.1,
    reviews: 9,
    size: "S",
    category: "Women",
    oldPrice: 4248,
    newPrice: 1699,
    discount: 60,
    isTrending: false,
    inStock: true,
    delivery_time: "2-4 business days",
    fewLeft: false,
  },
  {
    _id: "8",
    itemName: "Puma",
    image: "https://img.freepik.com/premium-psd/man-wearing-black-t-shirt-mockup-changeable-background_698054-911.jpg?size=626&ext=jpg",
    description: "Comfortable and breathable shorts for men.",
    rating: 4.6,
    reviews: 11,
    size: "M",
    category: "Men",
    oldPrice: 1599,
    newPrice: 447,
    discount: 68,
    isTrending: true,
    inStock: true,
    delivery_time: "2-4 business days",
    fewLeft: true,
  },
  {
    _id: "9",
    itemName: "Indo Era",
    image: "https://img.freepik.com/premium-photo/beautiful-smiling-woman-wearing-modern-trendy-dress_208024-705.jpg?size=626&ext=jpg",
    description: "A stylish and elegant dress for women.",
    rating: 3.8,
    reviews: 7,
    size: "XL",
    category: "Women",
    oldPrice: 1998,
    newPrice: 998,
    discount: 50,
    isTrending: false,
    inStock: false,
    delivery_time: "3-5 business days",
    fewLeft: true,
  },
  {
    _id: "10",
    itemName: "Wrogan",
    image: "https://img.freepik.com/premium-photo/full-length-handsome-young-man-looking-camera-smiling-while-standing-against-grey-background_425904-39817.jpg?size=626&ext=jpg",
    description: "Stylish and comfortable pants for men.",
    rating: 4.4,
    reviews: 14,
    size: "L",
    category: "Men",
    oldPrice: 1587,
    newPrice: 890,
    discount: 43,
    isTrending: true,
    inStock: true,
    delivery_time: "2-4 business days",
    fewLeft: false,
  },
  {
    _id: "11",
    itemName: "Biba",
    image: "https://img.freepik.com/free-photo/beautiful-woman-purple-sweater-skirt_1303-17492.jpg?size=626&ext=jpg",
    description: "A fashionable and versatile skirt for women.",
    rating: 4.2,
    reviews: 13,
    size: "M",
    category: "Women",
    oldPrice: 1599,
    newPrice: 1000,
    discount: 37,
    isTrending: false,
    inStock: true,
    delivery_time: "3-5 business days",
    fewLeft: false,
  },
  {
    _id: "12",

    itemName: "H&M",
    image: "https://img.freepik.com/premium-photo/clothes-schoolchildren-studio-portrait-little-boy-trendy-blue-sports-suit-white-background-cool-schoolboy-dressed-comfortable-children-s-sportswear-banner_417694-386.jpg?size=626&ext=jpg",
    description: "A cozy and warm hoodie for kids.",
    rating: 4.7,
    reviews: 8,
    size: "S",
    category: "Kids",
    oldPrice: 1099,
    newPrice: 619,
    discount: 43,
    isTrending: true,
    inStock: false,
    delivery_time: "2-4 business days",
    fewLeft: false,
  },
  {
    _id: "13",
    itemName: "Dennis Lingo",
    image: "https://img.freepik.com/free-photo/male-athlete-doing-fitness-training-workout-outside-gym_1328-4778.jpg?size=626&ext=jpg",
    description: "A warm and trendy hoodie for men.",
    rating: 3.9,
    reviews: 11,
    size: "L",
    category: "Men",
    oldPrice: 699,
    newPrice: 384,
    discount: 22,
    isTrending: false,
    inStock: true,
    delivery_time: "2-4 business days",
    fewLeft: false,
  },
  {
    _id: "14",
    itemName: "Indo Era",
    image: "https://img.freepik.com/free-photo/woman-red-jacket_1303-3718.jpg?size=626&ext=jpg",
    description: "A stylish and versatile jacket for women.",
    rating: 4.7,
    reviews: 15,
    size: "M",
    category: "Women",
    oldPrice: 3599,
    newPrice: 1799,
    discount: 50,
    isTrending: false,
    inStock: true,
    delivery_time: "3-5 business days",
    fewLeft: false,
  },
  {
    _id: "15",
    itemName: "BonOrganik",
    image: "https://img.freepik.com/free-photo/full-length-portrait-cute-little-kid-boy-stylish-jeans-clothes-smiling-standing-white-kids-fashion-concept_155003-20308.jpg?size=626&ext=jpg",
    description: "A classic and jeans for kids.",
    rating: 4.1,
    reviews: 9,
    size: "S",
    category: "Kids",
    oldPrice: 899,
    newPrice: 699,
    discount: 22,
    isTrending: false,
    inStock: true,
    delivery_time: "2-4 business days",
    fewLeft: true,
  },
  {
    _id: "16",
    itemName: "Roadster",
    image: "https://img.freepik.com/free-photo/medium-shot-smiley-kid-posing_23-2149853397.jpg?size=626&ext=jpg&ga=GA1.1.1963083236.1682951392&semt=ais",
    rating: 4.4,
    reviews: 12,
    size: "M",
    category: "Kids",
    oldPrice: 1599,
    newPrice: 1000,
    discount: 37,
    isTrending: true,
    description: "A cozy and stylish sweater for Kids.",
    delivery_time: "2-4 business days",
    inStock: true,
    fewLeft: false,
  },
  {
    _id: "17",
    itemName: "Kaya",
    image: "https://img.freepik.com/free-photo/cheerful-woman-jeans-hat-sunglasses-smiling-camera_171337-12136.jpg?size=626&ext=jpg&ga=GA1.2.1963083236.1682951392&semt=ais",
    rating: 3.7,
    reviews: 7,
    size: "L",
    category: "Women",
    oldPrice: 3599,
    newPrice: 1799,
    discount: 50,
    isTrending: false,
    description: "A comfortable and trendy pair of jeans for Women.",
    delivery_time: "3-5 business days",
    inStock: true,
    fewLeft: true,
  },
  {
    _id: "18",
    itemName: "Lyra",
    image: "https://img.freepik.com/free-photo/young-woman-beautiful-red-dress_1303-17506.jpg?size=626&ext=jpg",
    description: "An elegant and fashionable dress for women.",
    rating: 3.2,
    reviews: 5,
    size: "M",
    category: "Women",
    oldPrice: 2210,
    newPrice: 1810,
    discount: 18,
    isTrending: true,
    inStock: true,
    delivery_time: "3-5 business days",
    fewLeft: true,
  },
  {
    _id: "19",
    itemName: "Jordan",
    image: "https://img.freepik.com/premium-photo/studio-shot-handsome-bearded-man-ready-winter-isolated-against-white-background_251136-83947.jpg?size=626&ext=jpg&ga=GA1.1.1963083236.1682951392&semt=ais",
    rating: 4.6,
    reviews: 14,
    size: "XL",
    category: "Men",
    oldPrice: 1499,
    newPrice: 974,
    discount: 35,
    isTrending: true,
    description: "A warm and fashionable sweater for men.",
    delivery_time: "2-4 business days",
    inStock: true,
    fewLeft: false,
  },
  {
    _id: "20",
    itemName: "Kaya",
    image: "https://img.freepik.com/premium-psd/full-shot-woman-wearing-winter-clothes_23-2148933167.jpg?size=626&ext=jpg&ga=GA1.1.1963083236.1682951392&semt=ais",
    rating: 4.0,
    reviews: 9,
    size: "M",
    category: "Women",
    oldPrice: 1587,
    newPrice: 890,
    discount: 43,
    isTrending: false,
    description: "Comfortable and stylish joggers for women.",
    delivery_time: "3-5 business days",
    inStock: true,
    fewLeft: false,
  }
];

